### ISSUE TITLE
confirmation for sensitive commands

### ISSUE THREAD

**Issue by yorickvP** [serokell/ariadne#178]
> The fact that >remove really just removes selected wallet is scarry as hell, tho
> I would require to enter the wallet name or some CLI variant of captcha =)

Maybe `remove yes:really`

**Comment by goodsoft** [comment]
Confirmation dialogs and `yes:really` params don't actually prevent accidentally removing things.
Adding some kind of time-limited "undo" mechanism would be much better user experience.

**Comment by tkerber** [comment]
I'd disagree. It very much does prevent removing things by tab-completing and pressing enter too fast. A time-limited undo also has downsides; for instance the wallet removal might be because I'm moving it to a more secure machine, in which case I definitly don't want it still to linger around without me knowing!

**Comment by gromakovsky** [comment]
We are disabling GitHub issues in favor of YouTrack (https://github.com/serokell/ariadne/tree/1574990946d8b8d3cef0c6df2f6a767c89856b0d#issue-tracker).
Corresponding issue in YouTrack is https://issues.serokell.io/issue/AD-207.
