### ISSUE TITLE
Be compatible with the Daedalus

### ISSUE THREAD

**Issue by vantuz-subhuman** [serokell/ariadne#180]
I don't think that trying to be "more standard" than the default main wallet for a cryptocurrency project is a smart move.

Generating mnemonics that not only NON-recoverable in the Daedalus but also NON-recoverable silently (meaning that I can recover it but will get **another Cardano wallet** in the result) is **NO-GO**. Users are tought to associate mnemonics with the wallet - for a user 12 words **IS** the wallet. Your software basically generates **different** Cardano wallet from the same 12 words. This is akin subverting the very basics of the normal user-experience and imo will cause nothing but confusion, problems, and complaints of lost funds.

Imo, whatever IOHK is using for wallet generation should be considered to be **the standard** for the Cardano project. So there's no "being more standard" than this. You may use any generation method for other cryptocurrency projects if they support it.

For now - it is basically a bug, because it causes different results in different programs that suppose **to follow the same protocol**.

**Comment by vantuz-subhuman** [comment]
Issue description refers to this discussion: https://t.me/AriadneWallet/53

**Comment by vantuz-subhuman** [comment]
The rule of thumb is easy: if a program wants to be considered "a valid Cardano wallet" - then it should be able to produce **valid Cardano mnemonics** that I then can restore in **any other valid Cardano wallet software**.

This **should be** and **will be** a standard for any program in the future. Once you are normally compatible with the Daedalus - I will say any other software developers that I should be able to restore their keys in both Daedalus or Ariadne, since Ariadne is also a "valid Cardano wallet". But for now - it is now.

Your program **may** provide a special separate option of "special Ariadne wallets" that are not compatible with the Daedalus (tho, I would strongly argue against such feature). But it should NOT be the default option and user should be MADE AWARE that he uses a non-compatible specific feature that may cause problems and confusion.

**Comment by vantuz-subhuman** [comment]
For context: https://github.com/input-output-hk/cardano-sl/pull/3043#issuecomment-395738278

**Comment by Pastafarianist** [comment]
Thank you for taking your time to try out Ariadne!

Ariadne's mnemonic is not identical to the one that is used in Daedalus because Ariadne uses BIP-39 for converting random seed into a mnemonic, while Daedalus uses an ad-hoc custom scheme. For the beta, we decided to append a special keyword to the end of the mnemonic (`ariadne-v0`). Admittedly, a user could decide that this keyword can be stripped, so we are looking for a different way to make it clear that the mnemonics in Ariadne and Daedalus are different.

Currently, the `restore` command in Ariadne supports both Ariadne and Daedalus mnemonics. So at this moment import from Daedalus is possible. However, as we are moving from the Daedalus scheme of generating addresses to BIP-44 (which is the one most widely adopted in the cryptocurrency community), the previously existing straightforward way of importing wallets generated in Daedalus will not be possible anymore. We are looking into ways to provide seamless import, and considering two options: offering to create a transaction from the old wallet to the new one or importing these addresses directly and allowing transactions from them, but without first-class support that BIP-44 compliant addresses enjoy.

Export to Daedalus unfortunately isn't possible. Daedalus is not BIP-44 compliant, so it won't be able to import Ariadne's wallet anyway, not without substantial changes. We want to independently implement a Cardano wallet as we think it should be implemented, not another Daedalus. Hope you agree there is no need for two of them.

Furthermore, there is no notion of a *valid Cardano mnemonic*, there can only be a notion of a *valid Daedalus mnemonic*. Our mnemonics follow BIP-39. If you think that Daedalus' non-standard way of using mnemonic is better, please provide a reason why. Merely the fact that IOHK uses it is not a valid reason. We would like to improve upon Daedalus, not just repeat quirks it might have, and that includes better standards compliance.

The benefit of being standard-compliant is primarily compatibility with hardware wallets, which already implement both BIP-39 and BIP-44. In addition to that, BIP-44 provides an important advantage in that by merely looking at an address, we can determine whether it is a change address or not. In order to accomplish the same, Daedalus has to store extra data obtained from traversing the entire blockchain.

Hope that makes sense.

**Comment by SebastienGllmt** [comment]
Just an FYI BIP-44 support was in the works at some point (not sure if completed or still in the works) but I believe it is exposed in the wallet as an "external wallet" API endpoint since they needed this for hardware wallets.
